- name: Copy Weave shell script
  copy: src=files/weave dest=/usr/bin/weave owner=root group=root mode=0755

- name: Check weave status
  shell: /usr/bin/weave status
  register: weave_status
  changed_when: false #Since this is just info gathering, no need to report the change
  ignore_errors: yes

- name: Start Weave Router
  shell: /usr/bin/weave launch-router --ipalloc-range 10.2.0.0/16 --ipalloc-default-subnet 10.2.1.0/24 --dns-domain={{ dns_domain }} {{ groups.slaves | join(' ') | replace(inventory_hostname, "") }}
  when: "weave_status.stdout.find('Service: router') == -1"

- name: Start Weave Plugin
  shell: /usr/bin/weave launch-plugin
  when: "weave_status.stdout.find('Service: plugin') == -1"