---
- name: Add apt key for mesos
  apt_key: keyserver=keyserver.ubuntu.com id=E56151BF

- name: Set DISTRO variable
  shell: "lsb_release -is | tr '[:upper:]' '[:lower:]'"
  register: distro_var
  changed_when: false

- name: Set CODENAME variable
  shell: "lsb_release -cs"
  register: codename_var
  changed_when: false

- name: Add apt repository for mesos
  apt_repository: repo="deb http://repos.mesosphere.com/{{ distro_var.stdout }} {{ codename_var.stdout }} main" update_cache=yes

- name: Install mesos and marathon
  apt: name={{item}} update_cache=yes
  with_items:
    - mesos
    - marathon

- name: Install Chronos if requested
  apt: name=chronos
  when: install_chronos == true

- name: Set zookeeper ID
  template: src=zookeeper/myid.j2 dest=/etc/zookeeper/conf/myid
  notify:
    - Restart zookeeper

- name: Append zookeeper IP addresses
  lineinfile: 
    dest: /etc/zookeeper/conf/zoo.cfg 
    line: "server.{{ hostvars[item].zoo_id }}={{ item }}:2888:3888"
    regexp: "^server.{{ hostvars[item].zoo_id }}"
  with_items: "{{ groups.masters }}"
  notify:
    - Restart zookeeper

- name: Set zookeeper address for mesos
  template: src=master/zk.j2 dest=/etc/mesos/zk
  notify:
    - Restart mesos-master
    - Restart marathon

- name: Stop mesos-slave
  service: name=mesos-slave state=stopped

- name: Disable mesos-slave
  copy: src=mesos-slave.override dest=/etc/init/mesos-slave.override

- name: Set LIBPROCESS_IP env
  lineinfile:
    dest: /etc/default/mesos-master
    regexp: "^LIBPROCESS_IP"
    line: "LIBPROCESS_IP={{ inventory_hostname }}"
  notify:
    - Restart mesos-master

- name: Set LIBPROCESS_ADVERTISE_IP env
  lineinfile:
    dest: /etc/default/mesos-master
    regexp: "^LIBPROCESS_ADVERTISE_IP"
    line: "LIBPROCESS_ADVERTISE_IP={{ inventory_hostname }}"
  notify:
    - Restart mesos-master

- name: Start services
  service: name={{item}} state=started
  with_items:
    - zookeeper
    - mesos-master
    - marathon

- name: Start Chronos
  service: name=chronos state=started
  when: install_chronos == true